-- ============================================================
-- File 05: Agency ATS - clients, mandates, submittals, placements, fee terms
-- ============================================================

CREATE TABLE agency.clients (
  tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), name text NOT NULL, industry text, contract_type contract_type_enum NOT NULL, status client_status_enum NOT NULL DEFAULT 'active', billing_terms text, default_branding_id uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, lock_version bigint NOT NULL DEFAULT 0,
  PRIMARY KEY(id), CONSTRAINT uq_clients_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_clients_tenant_name UNIQUE(tenant_id,name), CONSTRAINT fk_clients_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id), CONSTRAINT fk_clients_branding FOREIGN KEY(tenant_id,default_branding_id) REFERENCES tenant.tenant_branding(tenant_id,id)
);
CREATE TABLE agency.client_domains (tenant_id uuid NOT NULL, client_id uuid NOT NULL, domain citext NOT NULL, is_primary boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,client_id,domain), CONSTRAINT fk_client_domains_client FOREIGN KEY(tenant_id,client_id) REFERENCES agency.clients(tenant_id,id));
CREATE UNIQUE INDEX uq_client_domains_one_primary ON agency.client_domains(tenant_id,client_id) WHERE is_primary;
CREATE TABLE agency.client_contacts (
  tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), client_id uuid NOT NULL, name text NOT NULL, email citext NOT NULL, phone_e164 text, role_title text, portal_access_enabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
  PRIMARY KEY(id), CONSTRAINT uq_client_contacts_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_client_contacts_email UNIQUE(tenant_id,client_id,email), CONSTRAINT fk_client_contacts_client FOREIGN KEY(tenant_id,client_id) REFERENCES agency.clients(tenant_id,id)
);
CREATE TABLE agency.client_portal_users (
  tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), client_id uuid NOT NULL, contact_id uuid NOT NULL, email citext NOT NULL, access_scope text NOT NULL CHECK(access_scope IN ('specific_mandates','all_active_mandates')), status tenant_user_status_enum NOT NULL DEFAULT 'invited', last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
  PRIMARY KEY(id), CONSTRAINT uq_client_portal_users_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_client_portal_users_contact UNIQUE(tenant_id,contact_id), CONSTRAINT fk_client_portal_users_client FOREIGN KEY(tenant_id,client_id) REFERENCES agency.clients(tenant_id,id), CONSTRAINT fk_client_portal_users_contact FOREIGN KEY(tenant_id,contact_id) REFERENCES agency.client_contacts(tenant_id,id)
);
CREATE TABLE agency.external_competing_agencies (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), name text NOT NULL, domain citext, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_external_competing_agencies_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_external_competing_agencies_name UNIQUE(tenant_id,name), CONSTRAINT fk_external_competing_agencies_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id));
CREATE TABLE agency.competitor_conflicts (tenant_id uuid NOT NULL, client_a_id uuid NOT NULL, client_b_id uuid NOT NULL, reason text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,client_a_id,client_b_id), CONSTRAINT fk_competitor_conflicts_a FOREIGN KEY(tenant_id,client_a_id) REFERENCES agency.clients(tenant_id,id), CONSTRAINT fk_competitor_conflicts_b FOREIGN KEY(tenant_id,client_b_id) REFERENCES agency.clients(tenant_id,id), CONSTRAINT chk_competitor_conflicts_order CHECK(client_a_id < client_b_id));

CREATE TABLE agency.mandates (
  tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), client_id uuid NOT NULL, mandate_number text NOT NULL, title text NOT NULL, headcount integer NOT NULL CHECK(headcount > 0), fee_structure fee_structure_enum NOT NULL, exclusivity exclusivity_enum NOT NULL, target_fill_date date, status mandate_status_enum NOT NULL DEFAULT 'draft', owner_user_id uuid, opened_at timestamptz, closed_at timestamptz, cancellation_reason text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, lock_version bigint NOT NULL DEFAULT 0,
  PRIMARY KEY(id), CONSTRAINT uq_mandates_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_mandates_number UNIQUE(tenant_id,mandate_number), CONSTRAINT fk_mandates_client FOREIGN KEY(tenant_id,client_id) REFERENCES agency.clients(tenant_id,id), CONSTRAINT fk_mandates_owner FOREIGN KEY(tenant_id,owner_user_id) REFERENCES tenant.users(tenant_id,id)
);
ALTER TABLE tenant.talent_pool_entry_mandates ADD CONSTRAINT fk_talent_pool_entry_mandates_mandate FOREIGN KEY (tenant_id, mandate_id) REFERENCES agency.mandates(tenant_id,id);
CREATE TABLE agency.mandate_competing_agencies (tenant_id uuid NOT NULL, mandate_id uuid NOT NULL, external_competing_agency_id uuid NOT NULL, risk_note text, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,mandate_id,external_competing_agency_id), CONSTRAINT fk_mandate_competing_agencies_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id), CONSTRAINT fk_mandate_competing_agencies_agency FOREIGN KEY(tenant_id,external_competing_agency_id) REFERENCES agency.external_competing_agencies(tenant_id,id));
CREATE TABLE agency.mandate_fee_terms (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), mandate_id uuid NOT NULL, term_type fee_structure_enum NOT NULL, percentage percent_0_100, flat_amount positive_money, currency currency_code NOT NULL DEFAULT 'USD', milestone_name text, milestone_order integer, due_event text CHECK(due_event IS NULL OR due_event IN ('signing','shortlist','interview','placement','start_date','guarantee_clear')), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_mandate_fee_terms_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_mandate_fee_terms_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id), CONSTRAINT chk_mandate_fee_terms_amount CHECK((term_type='percentage_of_salary' AND percentage IS NOT NULL AND flat_amount IS NULL) OR (term_type IN ('flat_fee','retainer','time_and_materials') AND flat_amount IS NOT NULL)));
CREATE TABLE agency.retainer_milestones (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), mandate_id uuid NOT NULL, fee_term_id uuid, milestone_order integer NOT NULL CHECK(milestone_order>0), name text NOT NULL, trigger_event text NOT NULL, amount positive_money NOT NULL, currency currency_code NOT NULL DEFAULT 'USD', status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','invoiced','paid','waived')), triggered_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_retainer_milestones_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_retainer_milestones_order UNIQUE(tenant_id,mandate_id,milestone_order), CONSTRAINT fk_retainer_milestones_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id), CONSTRAINT fk_retainer_milestones_fee_term FOREIGN KEY(tenant_id,fee_term_id) REFERENCES agency.mandate_fee_terms(tenant_id,id));
CREATE TABLE agency.client_portal_user_mandates (tenant_id uuid NOT NULL, portal_user_id uuid NOT NULL, mandate_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,portal_user_id,mandate_id), CONSTRAINT fk_client_portal_user_mandates_user FOREIGN KEY(tenant_id,portal_user_id) REFERENCES agency.client_portal_users(tenant_id,id), CONSTRAINT fk_client_portal_user_mandates_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id));

CREATE TABLE agency.submittals (
  tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), mandate_id uuid NOT NULL, candidate_id uuid NOT NULL, submitted_by_user_id uuid NOT NULL, submitted_at timestamptz, status submittal_status_enum NOT NULL DEFAULT 'draft', direct_apply_attestation text, competitor_conflict_overridden boolean NOT NULL DEFAULT false, competitor_conflict_override_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, lock_version bigint NOT NULL DEFAULT 0,
  PRIMARY KEY(id), CONSTRAINT uq_submittals_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_submittals_candidate_mandate UNIQUE(tenant_id,candidate_id,mandate_id), CONSTRAINT fk_submittals_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id), CONSTRAINT fk_submittals_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id), CONSTRAINT fk_submittals_submitted_by FOREIGN KEY(tenant_id,submitted_by_user_id) REFERENCES tenant.users(tenant_id,id), CONSTRAINT chk_submittals_conflict_override CHECK (competitor_conflict_overridden = false OR competitor_conflict_override_reason IS NOT NULL)
);
CREATE TABLE agency.submittal_profile_snapshots (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), submittal_id uuid NOT NULL, snapshot_version integer NOT NULL CHECK(snapshot_version>0), resume_document_id uuid, rendered_profile_uri text, created_by_user_id uuid, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_submittal_profile_snapshots_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_submittal_profile_snapshots_version UNIQUE(tenant_id,submittal_id,snapshot_version), CONSTRAINT fk_submittal_profile_snapshots_submittal FOREIGN KEY(tenant_id,submittal_id) REFERENCES agency.submittals(tenant_id,id), CONSTRAINT fk_submittal_profile_snapshots_resume FOREIGN KEY(tenant_id,resume_document_id) REFERENCES tenant.candidate_documents(tenant_id,id), CONSTRAINT fk_submittal_profile_snapshots_created_by FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE agency.submittal_profile_fields (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), snapshot_id uuid NOT NULL, field_key text NOT NULL, field_value text, is_redacted boolean NOT NULL DEFAULT false, redaction_reason text, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_submittal_profile_fields_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_submittal_profile_fields_key UNIQUE(tenant_id,snapshot_id,field_key), CONSTRAINT fk_submittal_profile_fields_snapshot FOREIGN KEY(tenant_id,snapshot_id) REFERENCES agency.submittal_profile_snapshots(tenant_id,id));
CREATE TABLE agency.submittal_feedback (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), submittal_id uuid NOT NULL, client_contact_id uuid NOT NULL, rating numeric(3,2) CHECK(rating BETWEEN 1 AND 5), decision text NOT NULL CHECK(decision IN ('advance','reject','hold','needs_more_info')), comments text, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_submittal_feedback_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_submittal_feedback_submittal FOREIGN KEY(tenant_id,submittal_id) REFERENCES agency.submittals(tenant_id,id), CONSTRAINT fk_submittal_feedback_contact FOREIGN KEY(tenant_id,client_contact_id) REFERENCES agency.client_contacts(tenant_id,id));

CREATE TABLE agency.placements (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), submittal_id uuid NOT NULL, candidate_id uuid NOT NULL, mandate_id uuid NOT NULL, placed_at timestamptz NOT NULL DEFAULT now(), start_date date, final_salary positive_money, currency currency_code NOT NULL DEFAULT 'USD', fee_amount positive_money NOT NULL, guarantee_status guarantee_status_enum NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_placements_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_placements_submittal UNIQUE(tenant_id,submittal_id), CONSTRAINT fk_placements_submittal FOREIGN KEY(tenant_id,submittal_id) REFERENCES agency.submittals(tenant_id,id), CONSTRAINT fk_placements_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id), CONSTRAINT fk_placements_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id));
CREATE TABLE agency.placement_fee_term_snapshots (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), placement_id uuid NOT NULL, source_fee_term_id uuid, term_type fee_structure_enum NOT NULL, percentage percent_0_100, flat_amount positive_money, currency currency_code NOT NULL, snapshot_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_placement_fee_term_snapshots_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_placement_fee_term_snapshots_placement FOREIGN KEY(tenant_id,placement_id) REFERENCES agency.placements(tenant_id,id), CONSTRAINT fk_placement_fee_term_snapshots_source FOREIGN KEY(tenant_id,source_fee_term_id) REFERENCES agency.mandate_fee_terms(tenant_id,id));
CREATE TABLE agency.placement_guarantees (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), placement_id uuid NOT NULL, guarantee_days integer NOT NULL CHECK(guarantee_days>=0), starts_at date NOT NULL, ends_at date NOT NULL, status guarantee_status_enum NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_placement_guarantees_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_placement_guarantees_placement FOREIGN KEY(tenant_id,placement_id) REFERENCES agency.placements(tenant_id,id), CONSTRAINT chk_placement_guarantees_period CHECK(ends_at >= starts_at));
