-- ============================================================
-- File 06: Workflow engine and strict entity reference registry
-- ============================================================

CREATE TABLE tenant.entity_references (
  tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), display_label text,
  candidate_id uuid, requisition_id uuid, application_id uuid, interview_id uuid, offer_id uuid, client_id uuid, mandate_id uuid, submittal_id uuid, placement_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_entity_references_tenant_id UNIQUE(tenant_id,id),
  CONSTRAINT fk_entity_references_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),
  CONSTRAINT fk_entity_references_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),
  CONSTRAINT fk_entity_references_requisition FOREIGN KEY(tenant_id,requisition_id) REFERENCES tenant.requisitions(tenant_id,id),
  CONSTRAINT fk_entity_references_application FOREIGN KEY(tenant_id,application_id) REFERENCES tenant.applications(tenant_id,id),
  CONSTRAINT fk_entity_references_interview FOREIGN KEY(tenant_id,interview_id) REFERENCES tenant.interviews(tenant_id,id),
  CONSTRAINT fk_entity_references_offer FOREIGN KEY(tenant_id,offer_id) REFERENCES tenant.offers(tenant_id,id),
  CONSTRAINT fk_entity_references_client FOREIGN KEY(tenant_id,client_id) REFERENCES agency.clients(tenant_id,id),
  CONSTRAINT fk_entity_references_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id),
  CONSTRAINT fk_entity_references_submittal FOREIGN KEY(tenant_id,submittal_id) REFERENCES agency.submittals(tenant_id,id),
  CONSTRAINT fk_entity_references_placement FOREIGN KEY(tenant_id,placement_id) REFERENCES agency.placements(tenant_id,id)
);
CREATE TRIGGER trg_entity_references_one_of BEFORE INSERT OR UPDATE ON tenant.entity_references FOR EACH ROW EXECUTE FUNCTION app.validate_one_of_refs();

CREATE TABLE tenant.workflow_templates (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), template_key citext NOT NULL, name text NOT NULL, status wf_template_status_enum NOT NULL DEFAULT 'draft', version integer NOT NULL DEFAULT 1 CHECK(version>0), owner_user_id uuid, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, lock_version bigint NOT NULL DEFAULT 0, PRIMARY KEY(id), CONSTRAINT uq_workflow_templates_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_workflow_templates_key_version UNIQUE(tenant_id,template_key,version), CONSTRAINT fk_workflow_templates_owner FOREIGN KEY(tenant_id,owner_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.workflow_template_validation_errors (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_template_id uuid NOT NULL, step_key text, error_code text NOT NULL, error_message text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_template_validation_errors_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_template_validation_errors_template FOREIGN KEY(tenant_id,workflow_template_id) REFERENCES tenant.workflow_templates(tenant_id,id));
CREATE TABLE tenant.workflow_canvas_nodes (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_template_id uuid NOT NULL, node_key text NOT NULL, step_type wf_step_type_enum NOT NULL, position_x numeric(10,2) NOT NULL, position_y numeric(10,2) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_canvas_nodes_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_workflow_canvas_nodes_key UNIQUE(tenant_id,workflow_template_id,node_key), CONSTRAINT fk_workflow_canvas_nodes_template FOREIGN KEY(tenant_id,workflow_template_id) REFERENCES tenant.workflow_templates(tenant_id,id));
CREATE TABLE tenant.workflow_canvas_edges (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_template_id uuid NOT NULL, from_node_id uuid NOT NULL, to_node_id uuid NOT NULL, label text, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_canvas_edges_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_canvas_edges_template FOREIGN KEY(tenant_id,workflow_template_id) REFERENCES tenant.workflow_templates(tenant_id,id), CONSTRAINT fk_workflow_canvas_edges_from FOREIGN KEY(tenant_id,from_node_id) REFERENCES tenant.workflow_canvas_nodes(tenant_id,id), CONSTRAINT fk_workflow_canvas_edges_to FOREIGN KEY(tenant_id,to_node_id) REFERENCES tenant.workflow_canvas_nodes(tenant_id,id), CONSTRAINT chk_workflow_canvas_edges_not_self CHECK(from_node_id <> to_node_id));
CREATE TABLE tenant.workflow_steps (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_template_id uuid NOT NULL, step_key citext NOT NULL, name text NOT NULL, step_type wf_step_type_enum NOT NULL, sort_order integer NOT NULL DEFAULT 0, sla_minutes integer CHECK(sla_minutes IS NULL OR sla_minutes>0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, PRIMARY KEY(id), CONSTRAINT uq_workflow_steps_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_workflow_steps_key UNIQUE(tenant_id,workflow_template_id,step_key), CONSTRAINT fk_workflow_steps_template FOREIGN KEY(tenant_id,workflow_template_id) REFERENCES tenant.workflow_templates(tenant_id,id));
CREATE TABLE tenant.workflow_step_settings (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_step_id uuid NOT NULL, setting_key citext NOT NULL, value_text text, value_number numeric(18,6), value_bool boolean, value_integer bigint, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_step_settings_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_workflow_step_settings_key UNIQUE(tenant_id,workflow_step_id,setting_key), CONSTRAINT fk_workflow_step_settings_step FOREIGN KEY(tenant_id,workflow_step_id) REFERENCES tenant.workflow_steps(tenant_id,id), CONSTRAINT chk_workflow_step_settings_one_value CHECK((CASE WHEN value_text IS NULL THEN 0 ELSE 1 END)+(CASE WHEN value_number IS NULL THEN 0 ELSE 1 END)+(CASE WHEN value_bool IS NULL THEN 0 ELSE 1 END)+(CASE WHEN value_integer IS NULL THEN 0 ELSE 1 END)=1));
CREATE TABLE tenant.workflow_step_approval_configs (tenant_id uuid NOT NULL, workflow_step_id uuid NOT NULL, resolution_mode approver_resolution_enum NOT NULL, approver_role_id uuid, approver_user_id uuid, org_hierarchy_levels integer CHECK(org_hierarchy_levels IS NULL OR org_hierarchy_levels>0), allow_delegation boolean NOT NULL DEFAULT true, PRIMARY KEY(tenant_id,workflow_step_id), CONSTRAINT fk_workflow_step_approval_configs_step FOREIGN KEY(tenant_id,workflow_step_id) REFERENCES tenant.workflow_steps(tenant_id,id), CONSTRAINT fk_workflow_step_approval_configs_role FOREIGN KEY(tenant_id,approver_role_id) REFERENCES tenant.roles(tenant_id,id), CONSTRAINT fk_workflow_step_approval_configs_user FOREIGN KEY(tenant_id,approver_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.workflow_step_ai_action_configs (tenant_id uuid NOT NULL, workflow_step_id uuid NOT NULL, action_type ai_action_type_enum NOT NULL, autonomy_mode ai_autonomy_mode_enum NOT NULL, confidence_threshold confidence_score, PRIMARY KEY(tenant_id,workflow_step_id), CONSTRAINT fk_workflow_step_ai_action_configs_step FOREIGN KEY(tenant_id,workflow_step_id) REFERENCES tenant.workflow_steps(tenant_id,id));
CREATE TABLE tenant.workflow_escalation_rules (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_step_id uuid NOT NULL, trigger_after_minutes integer NOT NULL CHECK(trigger_after_minutes>0), escalate_to_role_id uuid, escalate_to_user_id uuid, notification_template_key text, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_escalation_rules_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_escalation_rules_step FOREIGN KEY(tenant_id,workflow_step_id) REFERENCES tenant.workflow_steps(tenant_id,id), CONSTRAINT fk_workflow_escalation_rules_role FOREIGN KEY(tenant_id,escalate_to_role_id) REFERENCES tenant.roles(tenant_id,id), CONSTRAINT fk_workflow_escalation_rules_user FOREIGN KEY(tenant_id,escalate_to_user_id) REFERENCES tenant.users(tenant_id,id), CONSTRAINT chk_workflow_escalation_rules_target CHECK(escalate_to_role_id IS NOT NULL OR escalate_to_user_id IS NOT NULL));
CREATE TABLE tenant.workflow_transitions (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_template_id uuid NOT NULL, from_step_id uuid NOT NULL, to_step_id uuid NOT NULL, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_transitions_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_transitions_template FOREIGN KEY(tenant_id,workflow_template_id) REFERENCES tenant.workflow_templates(tenant_id,id), CONSTRAINT fk_workflow_transitions_from FOREIGN KEY(tenant_id,from_step_id) REFERENCES tenant.workflow_steps(tenant_id,id), CONSTRAINT fk_workflow_transitions_to FOREIGN KEY(tenant_id,to_step_id) REFERENCES tenant.workflow_steps(tenant_id,id), CONSTRAINT chk_workflow_transitions_not_self CHECK(from_step_id<>to_step_id));
CREATE TABLE tenant.workflow_transition_condition_groups (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), transition_id uuid NOT NULL, group_operator text NOT NULL CHECK(group_operator IN('AND','OR')), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_transition_condition_groups_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_transition_condition_groups_transition FOREIGN KEY(tenant_id,transition_id) REFERENCES tenant.workflow_transitions(tenant_id,id));
CREATE TABLE tenant.workflow_transition_conditions (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), condition_group_id uuid NOT NULL, field_key citext NOT NULL, operator condition_operator_enum NOT NULL, value_text text, value_number numeric(18,6), value_bool boolean, value_date date, PRIMARY KEY(id), CONSTRAINT uq_workflow_transition_conditions_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_transition_conditions_group FOREIGN KEY(tenant_id,condition_group_id) REFERENCES tenant.workflow_transition_condition_groups(tenant_id,id));
CREATE TABLE tenant.workflow_template_change_log (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_template_id uuid NOT NULL, changed_by_user_id uuid, change_reason text NOT NULL, diff_summary jsonb, changed_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_template_change_log_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_template_change_log_template FOREIGN KEY(tenant_id,workflow_template_id) REFERENCES tenant.workflow_templates(tenant_id,id), CONSTRAINT fk_workflow_template_change_log_user FOREIGN KEY(tenant_id,changed_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.workflow_simulation_runs (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_template_id uuid NOT NULL, entity_reference_id uuid NOT NULL, status sync_status_enum NOT NULL DEFAULT 'pending', started_by_user_id uuid, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, PRIMARY KEY(id), CONSTRAINT uq_workflow_simulation_runs_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_simulation_runs_template FOREIGN KEY(tenant_id,workflow_template_id) REFERENCES tenant.workflow_templates(tenant_id,id), CONSTRAINT fk_workflow_simulation_runs_entity FOREIGN KEY(tenant_id,entity_reference_id) REFERENCES tenant.entity_references(tenant_id,id), CONSTRAINT fk_workflow_simulation_runs_user FOREIGN KEY(tenant_id,started_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.workflow_simulation_steps (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), simulation_run_id uuid NOT NULL, step_id uuid NOT NULL, outcome text NOT NULL, sort_order integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_simulation_steps_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_simulation_steps_run FOREIGN KEY(tenant_id,simulation_run_id) REFERENCES tenant.workflow_simulation_runs(tenant_id,id), CONSTRAINT fk_workflow_simulation_steps_step FOREIGN KEY(tenant_id,step_id) REFERENCES tenant.workflow_steps(tenant_id,id));
CREATE TABLE tenant.workflow_instances (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_template_id uuid NOT NULL, entity_reference_id uuid NOT NULL, status wf_instance_status_enum NOT NULL DEFAULT 'running', current_step_id uuid, started_by_user_id uuid, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), lock_version bigint NOT NULL DEFAULT 0, PRIMARY KEY(id), CONSTRAINT uq_workflow_instances_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_instances_template FOREIGN KEY(tenant_id,workflow_template_id) REFERENCES tenant.workflow_templates(tenant_id,id), CONSTRAINT fk_workflow_instances_entity FOREIGN KEY(tenant_id,entity_reference_id) REFERENCES tenant.entity_references(tenant_id,id), CONSTRAINT fk_workflow_instances_current_step FOREIGN KEY(tenant_id,current_step_id) REFERENCES tenant.workflow_steps(tenant_id,id), CONSTRAINT fk_workflow_instances_started_by FOREIGN KEY(tenant_id,started_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.workflow_instance_context_values (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_instance_id uuid NOT NULL, context_key citext NOT NULL, value_text text, value_number numeric(18,6), value_bool boolean, value_date date, captured_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_instance_context_values_tenant_id UNIQUE(tenant_id,id), CONSTRAINT uq_workflow_instance_context_values_key UNIQUE(tenant_id,workflow_instance_id,context_key), CONSTRAINT fk_workflow_instance_context_values_instance FOREIGN KEY(tenant_id,workflow_instance_id) REFERENCES tenant.workflow_instances(tenant_id,id));
CREATE TABLE tenant.workflow_instance_history (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_instance_id uuid NOT NULL, from_step_id uuid, to_step_id uuid, action_key text NOT NULL, actor_user_id uuid, occurred_at timestamptz NOT NULL DEFAULT now(), comments text, PRIMARY KEY(id), CONSTRAINT uq_workflow_instance_history_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_instance_history_instance FOREIGN KEY(tenant_id,workflow_instance_id) REFERENCES tenant.workflow_instances(tenant_id,id), CONSTRAINT fk_workflow_instance_history_from FOREIGN KEY(tenant_id,from_step_id) REFERENCES tenant.workflow_steps(tenant_id,id), CONSTRAINT fk_workflow_instance_history_to FOREIGN KEY(tenant_id,to_step_id) REFERENCES tenant.workflow_steps(tenant_id,id), CONSTRAINT fk_workflow_instance_history_actor FOREIGN KEY(tenant_id,actor_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.workflow_condition_evaluations (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_history_id uuid NOT NULL, condition_id uuid, result boolean NOT NULL, actual_value text, evaluated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_workflow_condition_evaluations_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_workflow_condition_evaluations_history FOREIGN KEY(tenant_id,workflow_history_id) REFERENCES tenant.workflow_instance_history(tenant_id,id), CONSTRAINT fk_workflow_condition_evaluations_condition FOREIGN KEY(tenant_id,condition_id) REFERENCES tenant.workflow_transition_conditions(tenant_id,id));
CREATE TABLE tenant.approval_tasks (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workflow_instance_id uuid, entity_reference_id uuid NOT NULL, approver_user_id uuid NOT NULL, delegated_from_user_id uuid, status approval_status_enum NOT NULL DEFAULT 'pending', due_at timestamptz, decided_at timestamptz, decision_comment text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), lock_version bigint NOT NULL DEFAULT 0, PRIMARY KEY(id), CONSTRAINT uq_approval_tasks_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_approval_tasks_instance FOREIGN KEY(tenant_id,workflow_instance_id) REFERENCES tenant.workflow_instances(tenant_id,id), CONSTRAINT fk_approval_tasks_entity FOREIGN KEY(tenant_id,entity_reference_id) REFERENCES tenant.entity_references(tenant_id,id), CONSTRAINT fk_approval_tasks_approver FOREIGN KEY(tenant_id,approver_user_id) REFERENCES tenant.users(tenant_id,id), CONSTRAINT fk_approval_tasks_delegated_from FOREIGN KEY(tenant_id,delegated_from_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.ai_action_autonomy_configs (tenant_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), action_type ai_action_type_enum NOT NULL, scope_level config_scope_enum NOT NULL DEFAULT 'tenant', business_unit_id uuid, autonomy_mode ai_autonomy_mode_enum NOT NULL, confidence_threshold confidence_score, effective_from timestamptz NOT NULL DEFAULT now(), effective_to timestamptz, created_by_user_id uuid, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(id), CONSTRAINT uq_ai_action_autonomy_configs_tenant_id UNIQUE(tenant_id,id), CONSTRAINT fk_ai_action_autonomy_configs_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id), CONSTRAINT fk_ai_action_autonomy_configs_bu FOREIGN KEY(tenant_id,business_unit_id) REFERENCES tenant.business_units(tenant_id,id), CONSTRAINT fk_ai_action_autonomy_configs_user FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES tenant.users(tenant_id,id), CONSTRAINT chk_ai_action_autonomy_configs_period CHECK(effective_to IS NULL OR effective_to > effective_from));

INSERT INTO platform.allowed_jsonb_columns(schema_name, table_name, column_name, allowed_reason) VALUES
('tenant','workflow_template_change_log','diff_summary','Immutable workflow template change diff snapshot')
ON CONFLICT DO NOTHING;
