-- ============================================================
-- File 07: AI recruiter, interview bot, telephony, governance, usage
-- ============================================================

CREATE TABLE ai.recruiter_personas (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),name text NOT NULL,description text,default_tone text,autonomy_mode ai_autonomy_mode_enum NOT NULL DEFAULT 'human_approval_required',is_default boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,PRIMARY KEY(id),CONSTRAINT uq_recruiter_personas_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_recruiter_personas_name UNIQUE(tenant_id,name),CONSTRAINT fk_recruiter_personas_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id));
CREATE UNIQUE INDEX uq_recruiter_personas_default ON ai.recruiter_personas(tenant_id) WHERE is_default AND deleted_at IS NULL;
CREATE TABLE ai.persona_languages (tenant_id uuid NOT NULL,persona_id uuid NOT NULL,locale text NOT NULL,PRIMARY KEY(tenant_id,persona_id,locale),CONSTRAINT fk_persona_languages_persona FOREIGN KEY(tenant_id,persona_id) REFERENCES ai.recruiter_personas(tenant_id,id));
CREATE TABLE ai.persona_banned_topics (tenant_id uuid NOT NULL,persona_id uuid NOT NULL,topic_key text NOT NULL,PRIMARY KEY(tenant_id,persona_id,topic_key),CONSTRAINT fk_persona_banned_topics_persona FOREIGN KEY(tenant_id,persona_id) REFERENCES ai.recruiter_personas(tenant_id,id));
CREATE TABLE ai.persona_required_disclosures (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),persona_id uuid NOT NULL,disclosure_key text NOT NULL,disclosure_text text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_persona_required_disclosures_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_persona_required_disclosures_persona FOREIGN KEY(tenant_id,persona_id) REFERENCES ai.recruiter_personas(tenant_id,id));
CREATE TABLE ai.persona_escalation_rules (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),persona_id uuid NOT NULL,trigger_key text NOT NULL,condition_key text NOT NULL,action_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_persona_escalation_rules_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_persona_escalation_rules_persona FOREIGN KEY(tenant_id,persona_id) REFERENCES ai.recruiter_personas(tenant_id,id));
CREATE TABLE ai.persona_jurisdiction_disclosures (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),persona_id uuid NOT NULL,region region_enum NOT NULL,disclosure_text text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_persona_jurisdiction_disclosures_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_persona_jurisdiction_disclosures_region UNIQUE(tenant_id,persona_id,region),CONSTRAINT fk_persona_jurisdiction_disclosures_persona FOREIGN KEY(tenant_id,persona_id) REFERENCES ai.recruiter_personas(tenant_id,id));

CREATE TABLE ai.agent_identities (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),persona_id uuid,agent_key citext NOT NULL,display_name text NOT NULL,status text NOT NULL DEFAULT 'active' CHECK(status IN('active','disabled','deleted')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_agent_identities_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_agent_identities_key UNIQUE(tenant_id,agent_key),CONSTRAINT fk_agent_identities_persona FOREIGN KEY(tenant_id,persona_id) REFERENCES ai.recruiter_personas(tenant_id,id));
CREATE TABLE ai.agent_permissions (tenant_id uuid NOT NULL,agent_id uuid NOT NULL,permission_id uuid NOT NULL,PRIMARY KEY(tenant_id,agent_id,permission_id),CONSTRAINT fk_agent_permissions_agent FOREIGN KEY(tenant_id,agent_id) REFERENCES ai.agent_identities(tenant_id,id),CONSTRAINT fk_agent_permissions_permission FOREIGN KEY(tenant_id,permission_id) REFERENCES tenant.permissions(tenant_id,id));
CREATE TABLE ai.agent_business_units (tenant_id uuid NOT NULL,agent_id uuid NOT NULL,business_unit_id uuid NOT NULL,PRIMARY KEY(tenant_id,agent_id,business_unit_id),CONSTRAINT fk_agent_business_units_agent FOREIGN KEY(tenant_id,agent_id) REFERENCES ai.agent_identities(tenant_id,id),CONSTRAINT fk_agent_business_units_bu FOREIGN KEY(tenant_id,business_unit_id) REFERENCES tenant.business_units(tenant_id,id));

CREATE TABLE ai.prompt_templates (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),template_key citext NOT NULL,action_type ai_action_type_enum NOT NULL,version integer NOT NULL DEFAULT 1,template_text text NOT NULL,status wf_template_status_enum NOT NULL DEFAULT 'draft',model_definition_id uuid,created_by_user_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_prompt_templates_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_prompt_templates_key_version UNIQUE(tenant_id,template_key,version),CONSTRAINT fk_prompt_templates_model FOREIGN KEY(model_definition_id) REFERENCES platform.ai_model_definitions(id),CONSTRAINT fk_prompt_templates_user FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE ai.prompt_template_variables (tenant_id uuid NOT NULL,prompt_template_id uuid NOT NULL,variable_key citext NOT NULL,is_required boolean NOT NULL DEFAULT true,PRIMARY KEY(tenant_id,prompt_template_id,variable_key),CONSTRAINT fk_prompt_template_variables_template FOREIGN KEY(tenant_id,prompt_template_id) REFERENCES ai.prompt_templates(tenant_id,id));
CREATE TABLE ai.prompt_template_policy_flags (tenant_id uuid NOT NULL,prompt_template_id uuid NOT NULL,policy_key text NOT NULL,severity text NOT NULL CHECK(severity IN('low','medium','high','critical')),PRIMARY KEY(tenant_id,prompt_template_id,policy_key),CONSTRAINT fk_prompt_template_policy_flags_template FOREIGN KEY(tenant_id,prompt_template_id) REFERENCES ai.prompt_templates(tenant_id,id));

CREATE TABLE ai.sourcing_runs (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),requisition_id uuid,mandate_id uuid,persona_id uuid,started_by_user_id uuid,status sync_status_enum NOT NULL DEFAULT 'pending',started_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_sourcing_runs_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_sourcing_runs_requisition FOREIGN KEY(tenant_id,requisition_id) REFERENCES tenant.requisitions(tenant_id,id),CONSTRAINT fk_sourcing_runs_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id),CONSTRAINT fk_sourcing_runs_persona FOREIGN KEY(tenant_id,persona_id) REFERENCES ai.recruiter_personas(tenant_id,id),CONSTRAINT fk_sourcing_runs_user FOREIGN KEY(tenant_id,started_by_user_id) REFERENCES tenant.users(tenant_id,id),CONSTRAINT chk_sourcing_runs_subject CHECK((requisition_id IS NOT NULL)::int + (mandate_id IS NOT NULL)::int = 1));
CREATE TABLE ai.sourcing_criteria (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),sourcing_run_id uuid NOT NULL,criterion_key text NOT NULL,operator condition_operator_enum NOT NULL,value_text text,value_number numeric(18,6),value_bool boolean,weight numeric(6,3) NOT NULL DEFAULT 1 CHECK(weight>0),PRIMARY KEY(id),CONSTRAINT uq_sourcing_criteria_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_sourcing_criteria_run FOREIGN KEY(tenant_id,sourcing_run_id) REFERENCES ai.sourcing_runs(tenant_id,id));
CREATE TABLE ai.sourcing_sources (tenant_id uuid NOT NULL,sourcing_run_id uuid NOT NULL,source_key text NOT NULL,PRIMARY KEY(tenant_id,sourcing_run_id,source_key),CONSTRAINT fk_sourcing_sources_run FOREIGN KEY(tenant_id,sourcing_run_id) REFERENCES ai.sourcing_runs(tenant_id,id));

CREATE TABLE ai.match_scores (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),sourcing_run_id uuid,candidate_id uuid NOT NULL,requisition_id uuid,mandate_id uuid,score confidence_score NOT NULL,explanation text,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_match_scores_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_match_scores_run FOREIGN KEY(tenant_id,sourcing_run_id) REFERENCES ai.sourcing_runs(tenant_id,id),CONSTRAINT fk_match_scores_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_match_scores_requisition FOREIGN KEY(tenant_id,requisition_id) REFERENCES tenant.requisitions(tenant_id,id),CONSTRAINT fk_match_scores_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id));
CREATE TABLE ai.match_score_criteria (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),match_score_id uuid NOT NULL,criterion_key text NOT NULL,criterion_score confidence_score NOT NULL,evidence_text text,PRIMARY KEY(id),CONSTRAINT uq_match_score_criteria_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_match_score_criteria_score FOREIGN KEY(tenant_id,match_score_id) REFERENCES ai.match_scores(tenant_id,id));
CREATE TABLE ai.screening_results (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),application_id uuid,submittal_id uuid,candidate_id uuid NOT NULL,overall_score confidence_score NOT NULL,recommendation text NOT NULL CHECK(recommendation IN('advance','reject','hold','human_review')),confidence confidence_score NOT NULL,reasoning_summary text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_screening_results_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_screening_results_application FOREIGN KEY(tenant_id,application_id) REFERENCES tenant.applications(tenant_id,id),CONSTRAINT fk_screening_results_submittal FOREIGN KEY(tenant_id,submittal_id) REFERENCES agency.submittals(tenant_id,id),CONSTRAINT fk_screening_results_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT chk_screening_results_subject CHECK((application_id IS NOT NULL)::int + (submittal_id IS NOT NULL)::int <= 1));
CREATE TABLE ai.screening_criteria_results (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),screening_result_id uuid NOT NULL,criterion_key text NOT NULL,met boolean NOT NULL,score confidence_score,evidence_text text,PRIMARY KEY(id),CONSTRAINT uq_screening_criteria_results_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_screening_criteria_results_screening FOREIGN KEY(tenant_id,screening_result_id) REFERENCES ai.screening_results(tenant_id,id));
CREATE TABLE ai.ai_bias_flags (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),match_score_id uuid,screening_result_id uuid,interview_evaluation_id uuid,flag_key text NOT NULL,severity text NOT NULL CHECK(severity IN('low','medium','high','critical')),description text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_ai_bias_flags_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_ai_bias_flags_match FOREIGN KEY(tenant_id,match_score_id) REFERENCES ai.match_scores(tenant_id,id),CONSTRAINT fk_ai_bias_flags_screening FOREIGN KEY(tenant_id,screening_result_id) REFERENCES ai.screening_results(tenant_id,id),CONSTRAINT chk_ai_bias_flags_one_subject CHECK((match_score_id IS NOT NULL)::int+(screening_result_id IS NOT NULL)::int+(interview_evaluation_id IS NOT NULL)::int=1));

CREATE TABLE ai.ai_conversations (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),candidate_id uuid,application_id uuid,submittal_id uuid,persona_id uuid,channel notif_channel_enum NOT NULL,status text NOT NULL DEFAULT 'open' CHECK(status IN('open','closed','escalated')),started_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_ai_conversations_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_ai_conversations_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_ai_conversations_application FOREIGN KEY(tenant_id,application_id) REFERENCES tenant.applications(tenant_id,id),CONSTRAINT fk_ai_conversations_submittal FOREIGN KEY(tenant_id,submittal_id) REFERENCES agency.submittals(tenant_id,id),CONSTRAINT fk_ai_conversations_persona FOREIGN KEY(tenant_id,persona_id) REFERENCES ai.recruiter_personas(tenant_id,id));
CREATE TABLE ai.conversation_messages (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),conversation_id uuid NOT NULL,sender_type audit_actor_type_enum NOT NULL,sender_user_id uuid,message_text text NOT NULL,model_definition_id uuid,raw_model_response jsonb,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_conversation_messages_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_conversation_messages_conversation FOREIGN KEY(tenant_id,conversation_id) REFERENCES ai.ai_conversations(tenant_id,id),CONSTRAINT fk_conversation_messages_user FOREIGN KEY(tenant_id,sender_user_id) REFERENCES tenant.users(tenant_id,id),CONSTRAINT fk_conversation_messages_model FOREIGN KEY(model_definition_id) REFERENCES platform.ai_model_definitions(id));
CREATE TABLE ai.conversation_escalation_flags (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),conversation_id uuid NOT NULL,flag_key text NOT NULL,status text NOT NULL DEFAULT 'open' CHECK(status IN('open','resolved','dismissed')),created_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz,PRIMARY KEY(id),CONSTRAINT uq_conversation_escalation_flags_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_conversation_escalation_flags_conversation FOREIGN KEY(tenant_id,conversation_id) REFERENCES ai.ai_conversations(tenant_id,id));

CREATE TABLE ai.scheduling_requests (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),application_id uuid,submittal_id uuid,requested_by_user_id uuid,status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','proposed','confirmed','cancelled','failed')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_scheduling_requests_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_scheduling_requests_application FOREIGN KEY(tenant_id,application_id) REFERENCES tenant.applications(tenant_id,id),CONSTRAINT fk_scheduling_requests_submittal FOREIGN KEY(tenant_id,submittal_id) REFERENCES agency.submittals(tenant_id,id),CONSTRAINT fk_scheduling_requests_user FOREIGN KEY(tenant_id,requested_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE ai.scheduling_participants (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),scheduling_request_id uuid NOT NULL,user_id uuid,candidate_id uuid,client_contact_id uuid,participant_role text NOT NULL,required boolean NOT NULL DEFAULT true,PRIMARY KEY(id),CONSTRAINT uq_scheduling_participants_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_scheduling_participants_request FOREIGN KEY(tenant_id,scheduling_request_id) REFERENCES ai.scheduling_requests(tenant_id,id),CONSTRAINT fk_scheduling_participants_user FOREIGN KEY(tenant_id,user_id) REFERENCES tenant.users(tenant_id,id),CONSTRAINT fk_scheduling_participants_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_scheduling_participants_contact FOREIGN KEY(tenant_id,client_contact_id) REFERENCES agency.client_contacts(tenant_id,id),CONSTRAINT chk_scheduling_participants_one_party CHECK((user_id IS NOT NULL)::int+(candidate_id IS NOT NULL)::int+(client_contact_id IS NOT NULL)::int=1));
CREATE TABLE ai.scheduling_proposed_slots (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),scheduling_request_id uuid NOT NULL,start_at timestamptz NOT NULL,end_at timestamptz NOT NULL,timezone text NOT NULL,is_confirmed boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_scheduling_proposed_slots_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_scheduling_proposed_slots_request FOREIGN KEY(tenant_id,scheduling_request_id) REFERENCES ai.scheduling_requests(tenant_id,id),CONSTRAINT chk_scheduling_proposed_slots_time CHECK(end_at>start_at));
CREATE TABLE ai.scheduling_calendar_sync_statuses (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),scheduling_request_id uuid NOT NULL,participant_id uuid NOT NULL,connector_instance_id uuid,status sync_status_enum NOT NULL DEFAULT 'pending',external_event_id text,error_message text,updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_scheduling_calendar_sync_statuses_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_scheduling_calendar_sync_statuses_participant UNIQUE(tenant_id,scheduling_request_id,participant_id),CONSTRAINT fk_scheduling_calendar_sync_statuses_request FOREIGN KEY(tenant_id,scheduling_request_id) REFERENCES ai.scheduling_requests(tenant_id,id),CONSTRAINT fk_scheduling_calendar_sync_statuses_participant FOREIGN KEY(tenant_id,participant_id) REFERENCES ai.scheduling_participants(tenant_id,id));

CREATE TABLE ai.interview_sessions (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),interview_id uuid,candidate_id uuid NOT NULL,mode interview_type_enum NOT NULL,status ai_session_status_enum NOT NULL DEFAULT 'not_started',consent_record_id uuid,started_at timestamptz,completed_at timestamptz,recording_uri text,transcript_uri text,accommodation_notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_interview_sessions_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_interview_sessions_interview FOREIGN KEY(tenant_id,interview_id) REFERENCES tenant.interviews(tenant_id,id),CONSTRAINT fk_interview_sessions_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_interview_sessions_consent FOREIGN KEY(tenant_id,consent_record_id) REFERENCES tenant.consent_records(tenant_id,id));
CREATE TABLE ai.interview_question_sets (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),requisition_id uuid,mandate_id uuid,name text NOT NULL,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_interview_question_sets_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_interview_question_sets_req FOREIGN KEY(tenant_id,requisition_id) REFERENCES tenant.requisitions(tenant_id,id),CONSTRAINT fk_interview_question_sets_mandate FOREIGN KEY(tenant_id,mandate_id) REFERENCES agency.mandates(tenant_id,id));
CREATE TABLE ai.interview_questions (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),question_set_id uuid NOT NULL,question_text text NOT NULL,expected_answer_guide text,sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_interview_questions_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_interview_questions_set FOREIGN KEY(tenant_id,question_set_id) REFERENCES ai.interview_question_sets(tenant_id,id));
CREATE TABLE ai.interview_question_competencies (tenant_id uuid NOT NULL,question_id uuid NOT NULL,competency_id uuid NOT NULL,PRIMARY KEY(tenant_id,question_id,competency_id),CONSTRAINT fk_interview_question_competencies_question FOREIGN KEY(tenant_id,question_id) REFERENCES ai.interview_questions(tenant_id,id),CONSTRAINT fk_interview_question_competencies_comp FOREIGN KEY(tenant_id,competency_id) REFERENCES tenant.competency_taxonomy(tenant_id,id));
CREATE TABLE ai.interview_responses (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),interview_session_id uuid NOT NULL,question_id uuid,answer_text text,started_at timestamptz,ended_at timestamptz,confidence confidence_score,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_interview_responses_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_interview_responses_session FOREIGN KEY(tenant_id,interview_session_id) REFERENCES ai.interview_sessions(tenant_id,id),CONSTRAINT fk_interview_responses_question FOREIGN KEY(tenant_id,question_id) REFERENCES ai.interview_questions(tenant_id,id));
CREATE TABLE ai.interview_response_media (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),interview_response_id uuid NOT NULL,media_type text NOT NULL CHECK(media_type IN('audio','video','image','transcript')),storage_uri text NOT NULL,duration_ms integer CHECK(duration_ms IS NULL OR duration_ms>=0),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_interview_response_media_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_interview_response_media_response FOREIGN KEY(tenant_id,interview_response_id) REFERENCES ai.interview_responses(tenant_id,id));
CREATE TABLE ai.interview_evaluations (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),interview_session_id uuid NOT NULL,overall_score confidence_score NOT NULL,recommendation text NOT NULL CHECK(recommendation IN('advance','reject','hold','human_review')),reasoning_summary text NOT NULL,raw_model_response jsonb,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_interview_evaluations_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_interview_evaluations_session FOREIGN KEY(tenant_id,interview_session_id) REFERENCES ai.interview_sessions(tenant_id,id));
ALTER TABLE ai.ai_bias_flags ADD CONSTRAINT fk_ai_bias_flags_evaluation FOREIGN KEY(tenant_id,interview_evaluation_id) REFERENCES ai.interview_evaluations(tenant_id,id);
CREATE TABLE ai.interview_evaluation_competency_scores (tenant_id uuid NOT NULL,interview_evaluation_id uuid NOT NULL,competency_id uuid NOT NULL,score confidence_score NOT NULL,evidence_text text,PRIMARY KEY(tenant_id,interview_evaluation_id,competency_id),CONSTRAINT fk_interview_evaluation_competency_scores_eval FOREIGN KEY(tenant_id,interview_evaluation_id) REFERENCES ai.interview_evaluations(tenant_id,id),CONSTRAINT fk_interview_evaluation_competency_scores_comp FOREIGN KEY(tenant_id,competency_id) REFERENCES tenant.competency_taxonomy(tenant_id,id));
CREATE TABLE ai.interview_evaluation_flags (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),interview_evaluation_id uuid NOT NULL,flag_key text NOT NULL,severity text NOT NULL CHECK(severity IN('low','medium','high','critical')),details text,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_interview_evaluation_flags_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_interview_evaluation_flags_eval FOREIGN KEY(tenant_id,interview_evaluation_id) REFERENCES ai.interview_evaluations(tenant_id,id));
CREATE TABLE ai.interview_low_confidence_segments (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),interview_evaluation_id uuid NOT NULL,start_ms integer NOT NULL CHECK(start_ms>=0),end_ms integer NOT NULL CHECK(end_ms>start_ms),reason text NOT NULL,excluded_from_score boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_interview_low_confidence_segments_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_interview_low_confidence_segments_eval FOREIGN KEY(tenant_id,interview_evaluation_id) REFERENCES ai.interview_evaluations(tenant_id,id));

CREATE TABLE ai.tenant_telephony_configs (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),provider text NOT NULL,default_region region_enum NOT NULL,recording_enabled boolean NOT NULL DEFAULT true,transcription_enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_tenant_telephony_configs_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_tenant_telephony_configs_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id));
CREATE TABLE ai.telephony_numbers (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),telephony_config_id uuid NOT NULL,phone_number_e164 text NOT NULL,region region_enum NOT NULL,is_default boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_telephony_numbers_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_telephony_numbers_number UNIQUE(phone_number_e164),CONSTRAINT fk_telephony_numbers_config FOREIGN KEY(tenant_id,telephony_config_id) REFERENCES ai.tenant_telephony_configs(tenant_id,id));
CREATE TABLE ai.telephony_region_routes (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),telephony_config_id uuid NOT NULL,region region_enum NOT NULL,infrastructure_endpoint text NOT NULL,priority integer NOT NULL DEFAULT 1 CHECK(priority>0),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_telephony_region_routes_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_telephony_region_routes_config FOREIGN KEY(tenant_id,telephony_config_id) REFERENCES ai.tenant_telephony_configs(tenant_id,id));
CREATE TABLE ai.call_records (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),interview_session_id uuid,conversation_id uuid,direction call_direction_enum NOT NULL,from_number text,to_number text,provider_call_id text,status text NOT NULL,started_at timestamptz,ended_at timestamptz,duration_seconds integer CHECK(duration_seconds IS NULL OR duration_seconds>=0),recording_uri text,transcript_uri text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_call_records_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_call_records_session FOREIGN KEY(tenant_id,interview_session_id) REFERENCES ai.interview_sessions(tenant_id,id),CONSTRAINT fk_call_records_conversation FOREIGN KEY(tenant_id,conversation_id) REFERENCES ai.ai_conversations(tenant_id,id));
CREATE TABLE ai.call_real_time_flags (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),call_record_id uuid NOT NULL,flag_key text NOT NULL,timestamp_ms integer NOT NULL CHECK(timestamp_ms>=0),details text,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_call_real_time_flags_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_call_real_time_flags_call FOREIGN KEY(tenant_id,call_record_id) REFERENCES ai.call_records(tenant_id,id));
CREATE TABLE ai.call_quality_metrics (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),call_record_id uuid NOT NULL,metric_key text NOT NULL,metric_value numeric(18,6) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_call_quality_metrics_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_call_quality_metrics_key UNIQUE(tenant_id,call_record_id,metric_key),CONSTRAINT fk_call_quality_metrics_call FOREIGN KEY(tenant_id,call_record_id) REFERENCES ai.call_records(tenant_id,id));
CREATE TABLE ai.live_interview_calls (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),call_record_id uuid NOT NULL,interviewer_user_id uuid,status interview_status_enum NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_live_interview_calls_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_live_interview_calls_call FOREIGN KEY(tenant_id,call_record_id) REFERENCES ai.call_records(tenant_id,id),CONSTRAINT fk_live_interview_calls_interviewer FOREIGN KEY(tenant_id,interviewer_user_id) REFERENCES tenant.users(tenant_id,id));

CREATE TABLE ai.ai_usage_events (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),model_definition_id uuid,action_type ai_action_type_enum NOT NULL,source usage_source_enum NOT NULL,input_tokens integer NOT NULL DEFAULT 0 CHECK(input_tokens>=0),output_tokens integer NOT NULL DEFAULT 0 CHECK(output_tokens>=0),audio_seconds integer NOT NULL DEFAULT 0 CHECK(audio_seconds>=0),cost_amount positive_money,currency currency_code DEFAULT 'USD',occurred_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id,occurred_at),CONSTRAINT uq_ai_usage_events_tenant_id UNIQUE(tenant_id,id,occurred_at),CONSTRAINT fk_ai_usage_events_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_ai_usage_events_model FOREIGN KEY(model_definition_id) REFERENCES platform.ai_model_definitions(id)) PARTITION BY RANGE(occurred_at);
CREATE TABLE ai.ai_usage_events_default PARTITION OF ai.ai_usage_events DEFAULT;
CREATE TABLE ai.joining_risk_scores (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),engagement_id uuid NOT NULL,candidate_id uuid NOT NULL,risk_score confidence_score NOT NULL,risk_level text NOT NULL CHECK(risk_level IN('low','medium','high','critical')),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_joining_risk_scores_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_joining_risk_scores_engagement FOREIGN KEY(tenant_id,engagement_id) REFERENCES tenant.pre_joining_engagements(tenant_id,id),CONSTRAINT fk_joining_risk_scores_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id));
CREATE TABLE ai.joining_risk_factors (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),joining_risk_score_id uuid NOT NULL,factor_key text NOT NULL,weight numeric(6,3) NOT NULL CHECK(weight>=0),signal_value text,evidence_text text,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_joining_risk_factors_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_joining_risk_factors_score FOREIGN KEY(tenant_id,joining_risk_score_id) REFERENCES ai.joining_risk_scores(tenant_id,id));

INSERT INTO platform.allowed_jsonb_columns(schema_name, table_name, column_name, allowed_reason) VALUES
('ai','conversation_messages','raw_model_response','Immutable raw model response snapshot'),
('ai','interview_evaluations','raw_model_response','Immutable raw model response snapshot')
ON CONFLICT DO NOTHING;
