-- ============================================================
-- File 08: Integration framework, events, webhook delivery, notification framework, HITL
-- ============================================================

CREATE TABLE platform.connector_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),provider_key citext NOT NULL,display_name text NOT NULL,category connector_category_enum NOT NULL,auth_type connector_auth_type_enum NOT NULL,status plan_status_enum NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT uq_connector_definitions_provider UNIQUE(provider_key));
CREATE TABLE platform.connector_operations (connector_definition_id uuid NOT NULL,operation_key citext NOT NULL,description text,PRIMARY KEY(connector_definition_id,operation_key),CONSTRAINT fk_connector_operations_definition FOREIGN KEY(connector_definition_id) REFERENCES platform.connector_definitions(id));
CREATE TABLE platform.connector_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),connector_definition_id uuid NOT NULL,version_label text NOT NULL,released_at timestamptz NOT NULL DEFAULT now(),deprecated_at timestamptz,sunset_at timestamptz,CONSTRAINT fk_connector_versions_definition FOREIGN KEY(connector_definition_id) REFERENCES platform.connector_definitions(id),CONSTRAINT uq_connector_versions_definition_version UNIQUE(connector_definition_id,version_label));
CREATE TABLE tenant.connector_instances (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),connector_definition_id uuid NOT NULL,connector_version_id uuid,status connector_status_enum NOT NULL DEFAULT 'pending_setup',credentials_ref text,created_by_user_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,PRIMARY KEY(id),CONSTRAINT uq_connector_instances_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_connector_instances_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_connector_instances_definition FOREIGN KEY(connector_definition_id) REFERENCES platform.connector_definitions(id),CONSTRAINT fk_connector_instances_version FOREIGN KEY(connector_version_id) REFERENCES platform.connector_versions(id),CONSTRAINT fk_connector_instances_created_by FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.connector_instance_settings (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),connector_instance_id uuid NOT NULL,setting_key citext NOT NULL,value_text text,value_number numeric(18,6),value_bool boolean,secret_ref text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_connector_instance_settings_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_connector_instance_settings_key UNIQUE(tenant_id,connector_instance_id,setting_key),CONSTRAINT fk_connector_instance_settings_instance FOREIGN KEY(tenant_id,connector_instance_id) REFERENCES tenant.connector_instances(tenant_id,id),CONSTRAINT chk_connector_instance_settings_one_value CHECK((value_text IS NOT NULL)::int+(value_number IS NOT NULL)::int+(value_bool IS NOT NULL)::int+(secret_ref IS NOT NULL)::int=1));
ALTER TABLE tenant.job_board_postings ADD CONSTRAINT fk_job_board_postings_connector FOREIGN KEY(tenant_id,connector_instance_id) REFERENCES tenant.connector_instances(tenant_id,id);

CREATE TABLE tenant.sync_jobs (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),connector_instance_id uuid NOT NULL,sync_type sync_type_enum NOT NULL,status sync_status_enum NOT NULL DEFAULT 'pending',external_cursor text,last_sync_at timestamptz,records_processed integer NOT NULL DEFAULT 0 CHECK(records_processed>=0),records_failed integer NOT NULL DEFAULT 0 CHECK(records_failed>=0),started_at timestamptz,completed_at timestamptz,error_message text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_sync_jobs_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_sync_jobs_instance FOREIGN KEY(tenant_id,connector_instance_id) REFERENCES tenant.connector_instances(tenant_id,id));
CREATE TABLE tenant.sync_job_records (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),sync_job_id uuid NOT NULL,external_record_id text NOT NULL,record_status sync_status_enum NOT NULL,platform_table text,platform_record_id uuid,error_message text,processed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_sync_job_records_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_sync_job_records_external UNIQUE(tenant_id,sync_job_id,external_record_id),CONSTRAINT fk_sync_job_records_job FOREIGN KEY(tenant_id,sync_job_id) REFERENCES tenant.sync_jobs(tenant_id,id));
CREATE TABLE tenant.webhook_events (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),connector_instance_id uuid,provider_event_id text NOT NULL,event_type text NOT NULL,signature_valid boolean NOT NULL DEFAULT false,payload jsonb NOT NULL,received_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz,status sync_status_enum NOT NULL DEFAULT 'pending',PRIMARY KEY(id),CONSTRAINT uq_webhook_events_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_webhook_events_provider UNIQUE(tenant_id,provider_event_id),CONSTRAINT fk_webhook_events_instance FOREIGN KEY(tenant_id,connector_instance_id) REFERENCES tenant.connector_instances(tenant_id,id));
CREATE TABLE tenant.webhook_subscriptions (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),name text NOT NULL,target_url text NOT NULL,signing_secret_ref text NOT NULL,status connector_status_enum NOT NULL DEFAULT 'connected',created_by_user_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,PRIMARY KEY(id),CONSTRAINT uq_webhook_subscriptions_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_webhook_subscriptions_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_webhook_subscriptions_user FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.webhook_subscription_event_types (tenant_id uuid NOT NULL,webhook_subscription_id uuid NOT NULL,event_type text NOT NULL,PRIMARY KEY(tenant_id,webhook_subscription_id,event_type),CONSTRAINT fk_webhook_subscription_event_types_subscription FOREIGN KEY(tenant_id,webhook_subscription_id) REFERENCES tenant.webhook_subscriptions(tenant_id,id));
CREATE TABLE tenant.calendar_events (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),connector_instance_id uuid,external_event_id text,title text NOT NULL,start_at timestamptz NOT NULL,end_at timestamptz NOT NULL,timezone text NOT NULL,location text,meeting_url text,status text NOT NULL DEFAULT 'confirmed' CHECK(status IN('tentative','confirmed','cancelled')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_calendar_events_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_calendar_events_connector FOREIGN KEY(tenant_id,connector_instance_id) REFERENCES tenant.connector_instances(tenant_id,id),CONSTRAINT chk_calendar_events_time CHECK(end_at>start_at));
CREATE TABLE tenant.calendar_event_attendees (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),calendar_event_id uuid NOT NULL,email citext NOT NULL,user_id uuid,candidate_id uuid,client_contact_id uuid,response_status approval_status_enum NOT NULL DEFAULT 'pending',is_required boolean NOT NULL DEFAULT true,PRIMARY KEY(id),CONSTRAINT uq_calendar_event_attendees_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_calendar_event_attendees_event FOREIGN KEY(tenant_id,calendar_event_id) REFERENCES tenant.calendar_events(tenant_id,id),CONSTRAINT fk_calendar_event_attendees_user FOREIGN KEY(tenant_id,user_id) REFERENCES tenant.users(tenant_id,id),CONSTRAINT fk_calendar_event_attendees_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_calendar_event_attendees_contact FOREIGN KEY(tenant_id,client_contact_id) REFERENCES agency.client_contacts(tenant_id,id));
CREATE TABLE tenant.hrms_field_mappings (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),connector_instance_id uuid NOT NULL,platform_field text NOT NULL,external_field text NOT NULL,transformation_rule_key text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_hrms_field_mappings_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_hrms_field_mappings_field UNIQUE(tenant_id,connector_instance_id,platform_field),CONSTRAINT fk_hrms_field_mappings_instance FOREIGN KEY(tenant_id,connector_instance_id) REFERENCES tenant.connector_instances(tenant_id,id));
CREATE TABLE tenant.hrms_sync_records (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),connector_instance_id uuid NOT NULL,candidate_id uuid,offer_id uuid,employee_external_id text,sync_status sync_status_enum NOT NULL DEFAULT 'pending',error_detail text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_hrms_sync_records_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_hrms_sync_records_instance FOREIGN KEY(tenant_id,connector_instance_id) REFERENCES tenant.connector_instances(tenant_id,id),CONSTRAINT fk_hrms_sync_records_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_hrms_sync_records_offer FOREIGN KEY(tenant_id,offer_id) REFERENCES tenant.offers(tenant_id,id));

CREATE TABLE events.event_outbox (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),aggregate_reference_id uuid, event_type text NOT NULL,payload jsonb NOT NULL,status sync_status_enum NOT NULL DEFAULT 'pending',occurred_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz,retry_count integer NOT NULL DEFAULT 0 CHECK(retry_count>=0),PRIMARY KEY(id),CONSTRAINT uq_event_outbox_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_event_outbox_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id));
CREATE TABLE events.domain_events (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),event_type text NOT NULL,entity_reference_id uuid,source_service text NOT NULL,payload jsonb NOT NULL,occurred_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id,occurred_at),CONSTRAINT uq_domain_events_tenant_id UNIQUE(tenant_id,id,occurred_at),CONSTRAINT fk_domain_events_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_domain_events_entity FOREIGN KEY(tenant_id,entity_reference_id) REFERENCES tenant.entity_references(tenant_id,id)) PARTITION BY RANGE(occurred_at);
CREATE TABLE events.domain_events_default PARTITION OF events.domain_events DEFAULT;
CREATE TABLE events.event_subscriptions (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),name text NOT NULL,target_url text NOT NULL,signing_secret_ref text NOT NULL,status connector_status_enum NOT NULL DEFAULT 'connected',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_event_subscriptions_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_event_subscriptions_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id));
CREATE TABLE events.event_subscription_event_types (tenant_id uuid NOT NULL,event_subscription_id uuid NOT NULL,event_type text NOT NULL,PRIMARY KEY(tenant_id,event_subscription_id,event_type),CONSTRAINT fk_event_subscription_event_types_subscription FOREIGN KEY(tenant_id,event_subscription_id) REFERENCES events.event_subscriptions(tenant_id,id));
CREATE TABLE events.event_delivery_attempts (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),event_subscription_id uuid NOT NULL,domain_event_id uuid,attempt_number integer NOT NULL CHECK(attempt_number>0),status sync_status_enum NOT NULL,response_status integer,response_body text,attempted_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_event_delivery_attempts_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_event_delivery_attempts_subscription FOREIGN KEY(tenant_id,event_subscription_id) REFERENCES events.event_subscriptions(tenant_id,id));
CREATE TABLE events.idempotency_records (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),idempotency_key text NOT NULL,request_hash text NOT NULL,status text NOT NULL CHECK(status IN('in_progress','completed','failed')),result_payload jsonb,created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,PRIMARY KEY(id),CONSTRAINT uq_idempotency_records_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_idempotency_records_key UNIQUE(tenant_id,idempotency_key),CONSTRAINT fk_idempotency_records_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT chk_idempotency_records_expires CHECK(expires_at>created_at));

CREATE TABLE tenant.review_items (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),source_module text NOT NULL,source_action_type ai_action_type_enum NOT NULL,entity_reference_id uuid NOT NULL,ai_output_text text NOT NULL,ai_output_raw_snapshot jsonb,ai_confidence confidence_score NOT NULL,ai_reasoning_summary text NOT NULL,status review_item_status_enum NOT NULL DEFAULT 'pending',assigned_to_user_id uuid,assigned_to_role_id uuid,sla_due_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),lock_version bigint NOT NULL DEFAULT 0,PRIMARY KEY(id),CONSTRAINT uq_review_items_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_review_items_entity FOREIGN KEY(tenant_id,entity_reference_id) REFERENCES tenant.entity_references(tenant_id,id),CONSTRAINT fk_review_items_user FOREIGN KEY(tenant_id,assigned_to_user_id) REFERENCES tenant.users(tenant_id,id),CONSTRAINT fk_review_items_role FOREIGN KEY(tenant_id,assigned_to_role_id) REFERENCES tenant.roles(tenant_id,id),CONSTRAINT chk_review_items_assignee CHECK(assigned_to_user_id IS NOT NULL OR assigned_to_role_id IS NOT NULL));
CREATE TABLE tenant.review_item_relations (tenant_id uuid NOT NULL,review_item_id uuid NOT NULL,related_review_item_id uuid NOT NULL,relation_key text NOT NULL,PRIMARY KEY(tenant_id,review_item_id,related_review_item_id),CONSTRAINT fk_review_item_relations_item FOREIGN KEY(tenant_id,review_item_id) REFERENCES tenant.review_items(tenant_id,id),CONSTRAINT fk_review_item_relations_related FOREIGN KEY(tenant_id,related_review_item_id) REFERENCES tenant.review_items(tenant_id,id));
CREATE TABLE tenant.human_decisions (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),review_item_id uuid NOT NULL,decision review_item_status_enum NOT NULL,original_ai_output_text text NOT NULL,modified_output_text text,reason_code text,free_text_comment text,decided_by_user_id uuid NOT NULL,decided_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_human_decisions_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_human_decisions_item FOREIGN KEY(tenant_id,review_item_id) REFERENCES tenant.review_items(tenant_id,id),CONSTRAINT fk_human_decisions_user FOREIGN KEY(tenant_id,decided_by_user_id) REFERENCES tenant.users(tenant_id,id));

CREATE TABLE notif.notification_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),template_key citext NOT NULL,category notif_category_enum NOT NULL,name text NOT NULL,is_system boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT uq_notification_templates_key UNIQUE(template_key));
CREATE TABLE notif.notification_template_channels (template_id uuid NOT NULL,channel notif_channel_enum NOT NULL,PRIMARY KEY(template_id,channel),CONSTRAINT fk_notification_template_channels_template FOREIGN KEY(template_id) REFERENCES notif.notification_templates(id));
CREATE TABLE notif.notification_template_variables (template_id uuid NOT NULL,variable_key citext NOT NULL,is_required boolean NOT NULL DEFAULT true,PRIMARY KEY(template_id,variable_key),CONSTRAINT fk_notification_template_variables_template FOREIGN KEY(template_id) REFERENCES notif.notification_templates(id));
CREATE TABLE notif.notification_template_contents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),template_id uuid NOT NULL,channel notif_channel_enum NOT NULL,locale text NOT NULL DEFAULT 'en',subject text,body_text text NOT NULL,body_html text,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT fk_notification_template_contents_template FOREIGN KEY(template_id) REFERENCES notif.notification_templates(id),CONSTRAINT uq_notification_template_contents_template_channel_locale UNIQUE(template_id,channel,locale));
CREATE TABLE tenant.notification_template_overrides (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),template_id uuid NOT NULL,is_active boolean NOT NULL DEFAULT true,created_by_user_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_notification_template_overrides_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_notification_template_overrides_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_notification_template_overrides_template FOREIGN KEY(template_id) REFERENCES notif.notification_templates(id),CONSTRAINT fk_notification_template_overrides_user FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.notification_template_override_contents (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),override_id uuid NOT NULL,channel notif_channel_enum NOT NULL,locale text NOT NULL DEFAULT 'en',subject text,body_text text NOT NULL,body_html text,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_notification_template_override_contents_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_notification_template_override_contents_locale UNIQUE(tenant_id,override_id,channel,locale),CONSTRAINT fk_notification_template_override_contents_override FOREIGN KEY(tenant_id,override_id) REFERENCES tenant.notification_template_overrides(tenant_id,id));
CREATE TABLE notif.notification_events (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),template_id uuid,category notif_category_enum NOT NULL,recipient_type notif_recipient_type_enum NOT NULL,user_id uuid,candidate_id uuid,client_contact_id uuid,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_notification_events_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_notification_events_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_notification_events_template FOREIGN KEY(template_id) REFERENCES notif.notification_templates(id),CONSTRAINT fk_notification_events_user FOREIGN KEY(tenant_id,user_id) REFERENCES tenant.users(tenant_id,id),CONSTRAINT fk_notification_events_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_notification_events_contact FOREIGN KEY(tenant_id,client_contact_id) REFERENCES agency.client_contacts(tenant_id,id));
CREATE TABLE notif.notification_event_variables (tenant_id uuid NOT NULL,notification_event_id uuid NOT NULL,variable_key citext NOT NULL,variable_value text NOT NULL,PRIMARY KEY(tenant_id,notification_event_id,variable_key),CONSTRAINT fk_notification_event_variables_event FOREIGN KEY(tenant_id,notification_event_id) REFERENCES notif.notification_events(tenant_id,id));
CREATE TABLE notif.notification_deliveries (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),notification_event_id uuid NOT NULL,channel notif_channel_enum NOT NULL,status notif_delivery_status_enum NOT NULL DEFAULT 'queued',provider_message_id text,queued_at timestamptz NOT NULL DEFAULT now(),sent_at timestamptz,delivered_at timestamptz,failed_at timestamptz,error_message text,PRIMARY KEY(id),CONSTRAINT uq_notification_deliveries_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_notification_deliveries_event FOREIGN KEY(tenant_id,notification_event_id) REFERENCES notif.notification_events(tenant_id,id));
CREATE TABLE notif.notification_delivery_attempts (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),notification_delivery_id uuid NOT NULL,attempt_number integer NOT NULL CHECK(attempt_number>0),status notif_delivery_status_enum NOT NULL,response_status integer,response_body text,attempted_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_notification_delivery_attempts_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_notification_delivery_attempts_delivery FOREIGN KEY(tenant_id,notification_delivery_id) REFERENCES notif.notification_deliveries(tenant_id,id));
CREATE TABLE tenant.notification_preferences (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),user_id uuid,candidate_id uuid,client_contact_id uuid,category notif_category_enum NOT NULL,enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_notification_preferences_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_notification_preferences_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_notification_preferences_user FOREIGN KEY(tenant_id,user_id) REFERENCES tenant.users(tenant_id,id),CONSTRAINT fk_notification_preferences_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_notification_preferences_contact FOREIGN KEY(tenant_id,client_contact_id) REFERENCES agency.client_contacts(tenant_id,id),CONSTRAINT chk_notification_preferences_one_subject CHECK((user_id IS NOT NULL)::int+(candidate_id IS NOT NULL)::int+(client_contact_id IS NOT NULL)::int=1));
CREATE TABLE tenant.notification_preference_channels (tenant_id uuid NOT NULL,notification_preference_id uuid NOT NULL,channel notif_channel_enum NOT NULL,enabled boolean NOT NULL DEFAULT true,PRIMARY KEY(tenant_id,notification_preference_id,channel),CONSTRAINT fk_notification_preference_channels_pref FOREIGN KEY(tenant_id,notification_preference_id) REFERENCES tenant.notification_preferences(tenant_id,id));
CREATE TABLE notif.suppression_list (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),recipient_email citext,recipient_phone_e164 text,channel notif_channel_enum NOT NULL,reason suppression_reason_enum NOT NULL,starts_at timestamptz NOT NULL DEFAULT now(),ends_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_suppression_list_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_suppression_list_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT chk_suppression_list_recipient CHECK(recipient_email IS NOT NULL OR recipient_phone_e164 IS NOT NULL));

INSERT INTO platform.allowed_jsonb_columns(schema_name, table_name, column_name, allowed_reason) VALUES
('tenant','webhook_events','payload','Immutable raw inbound webhook payload'),
('events','event_outbox','payload','Immutable raw outbound event payload'),
('events','domain_events','payload','Immutable raw domain event payload'),
('events','idempotency_records','result_payload','Immutable response snapshot for idempotency replay'),
('tenant','review_items','ai_output_raw_snapshot','Immutable raw AI output snapshot')
ON CONFLICT DO NOTHING;
