-- ============================================================
-- File 10: Reporting, analytics, compliance, retention, evidence
-- ============================================================
CREATE TABLE tenant.dashboards (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),name text NOT NULL,owner_user_id uuid,is_default boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,PRIMARY KEY(id),CONSTRAINT uq_dashboards_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_dashboards_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_dashboards_owner FOREIGN KEY(tenant_id,owner_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.dashboard_widgets (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),dashboard_id uuid NOT NULL,widget_key text NOT NULL,widget_type text NOT NULL,report_definition_id uuid,position_x integer NOT NULL DEFAULT 0,position_y integer NOT NULL DEFAULT 0,width integer NOT NULL CHECK(width>0),height integer NOT NULL CHECK(height>0),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_dashboard_widgets_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_dashboard_widgets_dashboard FOREIGN KEY(tenant_id,dashboard_id) REFERENCES tenant.dashboards(tenant_id,id));
CREATE TABLE tenant.dashboard_shares (tenant_id uuid NOT NULL,dashboard_id uuid NOT NULL,user_id uuid NOT NULL,can_edit boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,dashboard_id,user_id),CONSTRAINT fk_dashboard_shares_dashboard FOREIGN KEY(tenant_id,dashboard_id) REFERENCES tenant.dashboards(tenant_id,id),CONSTRAINT fk_dashboard_shares_user FOREIGN KEY(tenant_id,user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.report_definitions (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),report_key citext NOT NULL,name text NOT NULL,owner_user_id uuid,base_view text NOT NULL,default_format report_format_enum NOT NULL DEFAULT 'csv',schedule_cron text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,PRIMARY KEY(id),CONSTRAINT uq_report_definitions_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_report_definitions_key UNIQUE(tenant_id,report_key),CONSTRAINT fk_report_definitions_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_report_definitions_owner FOREIGN KEY(tenant_id,owner_user_id) REFERENCES tenant.users(tenant_id,id));
ALTER TABLE tenant.dashboard_widgets ADD CONSTRAINT fk_dashboard_widgets_report FOREIGN KEY(tenant_id,report_definition_id) REFERENCES tenant.report_definitions(tenant_id,id);
CREATE TABLE tenant.report_filters (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),report_definition_id uuid NOT NULL,field_key text NOT NULL,operator condition_operator_enum NOT NULL,value_text text,value_number numeric(18,6),value_bool boolean,value_date date,PRIMARY KEY(id),CONSTRAINT uq_report_filters_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_report_filters_report FOREIGN KEY(tenant_id,report_definition_id) REFERENCES tenant.report_definitions(tenant_id,id));
CREATE TABLE tenant.report_columns (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),report_definition_id uuid NOT NULL,column_key text NOT NULL,label text NOT NULL,sort_order integer NOT NULL DEFAULT 0,is_group_by boolean NOT NULL DEFAULT false,PRIMARY KEY(id),CONSTRAINT uq_report_columns_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_report_columns_key UNIQUE(tenant_id,report_definition_id,column_key),CONSTRAINT fk_report_columns_report FOREIGN KEY(tenant_id,report_definition_id) REFERENCES tenant.report_definitions(tenant_id,id));
CREATE TABLE tenant.report_schedule_recipients (tenant_id uuid NOT NULL,report_definition_id uuid NOT NULL,user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,report_definition_id,user_id),CONSTRAINT fk_report_schedule_recipients_report FOREIGN KEY(tenant_id,report_definition_id) REFERENCES tenant.report_definitions(tenant_id,id),CONSTRAINT fk_report_schedule_recipients_user FOREIGN KEY(tenant_id,user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE tenant.export_jobs (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),report_definition_id uuid,requested_by_user_id uuid NOT NULL,format report_format_enum NOT NULL,status sync_status_enum NOT NULL DEFAULT 'pending',result_uri text,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,PRIMARY KEY(id),CONSTRAINT uq_export_jobs_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_export_jobs_report FOREIGN KEY(tenant_id,report_definition_id) REFERENCES tenant.report_definitions(tenant_id,id),CONSTRAINT fk_export_jobs_user FOREIGN KEY(tenant_id,requested_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE analytics.metric_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),metric_key citext NOT NULL,display_name text NOT NULL,unit text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT uq_metric_definitions_key UNIQUE(metric_key));
CREATE TABLE analytics.dimension_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),dimension_key citext NOT NULL,display_name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT uq_dimension_definitions_key UNIQUE(dimension_key));
CREATE TABLE analytics.analytics_events (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),event_key text NOT NULL,entity_reference_id uuid,occurred_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id,occurred_at),CONSTRAINT uq_analytics_events_tenant_id UNIQUE(tenant_id,id,occurred_at),CONSTRAINT fk_analytics_events_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_analytics_events_entity FOREIGN KEY(tenant_id,entity_reference_id) REFERENCES tenant.entity_references(tenant_id,id)) PARTITION BY RANGE(occurred_at);
CREATE TABLE analytics.analytics_events_default PARTITION OF analytics.analytics_events DEFAULT;
CREATE TABLE analytics.analytics_event_metric_values (tenant_id uuid NOT NULL,analytics_event_id uuid NOT NULL,metric_definition_id uuid NOT NULL,metric_value numeric(18,6) NOT NULL,occurred_at timestamptz NOT NULL,PRIMARY KEY(tenant_id,analytics_event_id,metric_definition_id),CONSTRAINT fk_analytics_event_metric_values_metric FOREIGN KEY(metric_definition_id) REFERENCES analytics.metric_definitions(id));
CREATE TABLE analytics.analytics_event_dimension_values (tenant_id uuid NOT NULL,analytics_event_id uuid NOT NULL,dimension_definition_id uuid NOT NULL,dimension_value text NOT NULL,occurred_at timestamptz NOT NULL,PRIMARY KEY(tenant_id,analytics_event_id,dimension_definition_id),CONSTRAINT fk_analytics_event_dimension_values_dimension FOREIGN KEY(dimension_definition_id) REFERENCES analytics.dimension_definitions(id));
CREATE TABLE analytics.daily_metric_facts (tenant_id uuid NOT NULL,metric_definition_id uuid NOT NULL,fact_date date NOT NULL,dimension_hash text NOT NULL DEFAULT 'all',metric_value numeric(18,6) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,metric_definition_id,fact_date,dimension_hash),CONSTRAINT fk_daily_metric_facts_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_daily_metric_facts_metric FOREIGN KEY(metric_definition_id) REFERENCES analytics.metric_definitions(id));
CREATE TABLE compliance.retention_policies (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),resource_key text NOT NULL,retention_days integer NOT NULL CHECK(retention_days>0),archive_after_days integer CHECK(archive_after_days IS NULL OR archive_after_days>0),is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_retention_policies_tenant_id UNIQUE(tenant_id,id),CONSTRAINT uq_retention_policies_resource UNIQUE(tenant_id,resource_key),CONSTRAINT fk_retention_policies_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id));
CREATE TABLE compliance.legal_holds (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),candidate_id uuid,entity_reference_id uuid,reason text NOT NULL,status text NOT NULL DEFAULT 'active' CHECK(status IN('active','released')),placed_by_user_id uuid,placed_at timestamptz NOT NULL DEFAULT now(),released_at timestamptz,PRIMARY KEY(id),CONSTRAINT uq_legal_holds_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_legal_holds_candidate FOREIGN KEY(tenant_id,candidate_id) REFERENCES tenant.candidates(tenant_id,id),CONSTRAINT fk_legal_holds_entity FOREIGN KEY(tenant_id,entity_reference_id) REFERENCES tenant.entity_references(tenant_id,id),CONSTRAINT fk_legal_holds_user FOREIGN KEY(tenant_id,placed_by_user_id) REFERENCES tenant.users(tenant_id,id));
CREATE TABLE compliance.evidence_packages (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),framework compliance_framework_enum NOT NULL,period_start date NOT NULL,period_end date NOT NULL,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','collecting','ready','submitted','accepted')),created_by_user_id uuid,storage_uri text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_evidence_packages_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_evidence_packages_tenant FOREIGN KEY(tenant_id) REFERENCES platform.tenants(id),CONSTRAINT fk_evidence_packages_user FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES tenant.users(tenant_id,id),CONSTRAINT chk_evidence_packages_period CHECK(period_end>=period_start));
CREATE TABLE compliance.evidence_items (tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),evidence_package_id uuid NOT NULL,evidence_key text NOT NULL,source_table text,source_id uuid,storage_uri text,status sync_status_enum NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(id),CONSTRAINT uq_evidence_items_tenant_id UNIQUE(tenant_id,id),CONSTRAINT fk_evidence_items_package FOREIGN KEY(tenant_id,evidence_package_id) REFERENCES compliance.evidence_packages(tenant_id,id));
